### ISSUE TITLE
File preprocessing to avoid `QStringLiteral` and loss of sanity

### ISSUE THREAD

**Issue by KotzaBoss** [fiffty-50/openpilotlog#63]
After going up and down in `oplconstant.h` i have started seeing stars in the form of QStringLiterals.
It would ease developement boilerplate to separate syntax checking and add a custom preprocessing command to set any `"literal"` to `QStringLiteral("literal")`. That way the dev wont have to write it *every time*. The build tools will do it for him.

Clang and gcc have flags to check for syntax errors and exit. Should the error code be 0 it means that the code is syntactically valid and we can do text substitution to replace the literals to QStringLiterals. With python the substitution logic is 2 lines
```python
import re
new_content = re.sub(r'(?<!\()(".+")', 'QStringLiteral(\g<1>)', src)
```
![image](https://user-images.githubusercontent.com/69913906/105729611-b7fe5e80-5f2d-11eb-9558-a39324c132ab.png)

That requires setting up the CI/CD chain however so its no trivial task

**Comment by fiffty-50** [comment]
The problem here is that not every literal should be a QStringLiteral.

There are various examples, but from the top of my head:

- User-facing strings should use tr() instead of QStringLiteral
- If there is an overload for QLatin1String, using QStringLiteral is bad and QLatin1String should be used, for example:
  - `QString::append()`
  - Comparisons using the `==` operator should be done with QLatin1String as well
  - `QString::contains()`
  - strongly prefer when using concatenation of Literals (via QStringBuilder) 

So I'm afraid there is no one-size-fits-all solution.
