### ISSUE TITLE
Develop BackupWidget

### ISSUE THREAD

**Issue by fiffty-50** [fiffty-50/openpilotlog#69]
The purpose of the `BackupWidget` is to primarily enable backing up and restoring the database to and from `backupdir` as in **AStandardPaths**, but should also allow exporting and importing the database to an external path (a Pen Drive, a cloud folder etc.)

So what I have in mind is a widget containing the following:

- 'Backup Database' (or similar) button that creates a copy of the current database and places it in `backupdir`
- A view of available backups in `backupdir`, maybe a **QTableView** or **QListView** presenting the backup dates from which the user can select a backup.
- 'Restore Backup' (or similar) button that copies the selected backup from the list from `backupdir` to `DatabaseLocation`.
- `Delete Backup` to delete an outdated backup, a duplicate or do some 'housekeeping'
- Similar to `Backup` and `Restore`, the option to `Import` and `Export` the database, but instead of writing/reading to/from the `backupdir`, a QFileDialog (or similar) enables the user to choose the Location of the Backup.

Apart from that basic layout, we also need to think about how to verify that the file the user wants to import is valid, so we need to establish some requirements that a *file* must fulfill in order to be acceptable.

Nice to have: The list of available backups can display a few key dates about the backup itself when selecting a line from the QTableView, for example something like:

"Backup from 2021-02-12, 364 Flights with 748:33h Total Time, last Flight: KJFK-EDDF on 2021-01-03"

**Comment by KotzaBoss** [comment]
Let me comment on the main points of this widget so i can see if im on the right track or not
- Backup database to backupDir which i assume is a AStandardPath.
- Simple enough iterate over the backup files in the directory and post process them as necessary
- Self explanatory
- [...] or do some house keeping doesnt sound like something this widget should be responsible. Though housekeeping in it self is abit vague. What kind of cleanup are we talking about? Too old backups perhaps?
- So the whole point is to let the user choose their own backupDIr instead of our preset?

As far as valid files are concerned this needs some discussion because we need to know exactly what those files are.

The nice to have is just UI sugar, if we get the listing of the backups nice and clean then thats just another function when clicking one of the entries

**Comment by fiffty-50** [comment]
Yes to most of it!

> Housekeeping in itself is a bit vague.

By housekeeping I mean the user managing his backups. Let's say the user normally makes a weekly backup but only wants to keep a monthly backup for times further in the past because the list of backups keeps growing - that's where a `delete backup` button comes in.

I don't think we should automatically clean up backups after a certain period of time, that should always be a conscious choice.

> So the whole point is to let the user choose their own backupDIr instead of our preset?

Yes and no, there's two parts to that. 

### 1. Backup

- When the user hits the 'backup' button, a backup is created and put in the standard path, it then shows up in the list of available back-ups to 'roll back' the application to an earlier state.
- The user can select a backup from the list of backups in `backupDir` and hit "restore"
- This requires no manual intervention, backups are created and restored 'automatically' from the list of available backups in `backupDir`

### 2. Import/Export

- This can be used to transfer your database to another device, make an external backup on a disk, cloud storage etc.
- Imagine you're buying a new PC or re-installing windows, but want to take your logbook with you
- The user chooses the location the database file gets exported to / imported from

**Comment by KotzaBoss** [comment]
Ok i think i got it but still import export doesnt sound something a "backup" widget should do. What you have described sound like something you would find in the File option on the top bar of a program. Any way its more of a naming thing because these operations arent too different.
Do you have the ui side of the widget ready because if i set up the ui i may deviate from your current aesthetic. 
If not perhaps you can setup the ui vaguely so that i work on the behind logic.

**Comment by fiffty-50** [comment]
I don't have it set up yet, but I can do that. I'm not sure if I'll have time tomorrow, but by Thursday or latest Friday I should have something ready!

**Comment by fiffty-50** [comment]
Okay, ready to go!

![backupwidget](https://user-images.githubusercontent.com/32618887/108251009-3a59f700-7157-11eb-9874-adc8ea890908.png)

**Comment by KotzaBoss** [comment]
Excellent will get to work from tmrw
